# the name is required, because when it is not set docker uses the directory name as default
# and since this compose file is linked to multiple directories that woulkd be a problem
name: homeassistant

services:

  homeassistant:
    image: homeassistant/home-assistant:latest
    container_name: "homeassistant"
    restart: always
    stop_grace_period: 2m
    volumes:
      - "/containers/homeassistant:/config"
      # - "/opt/letsencrypt:/letsencrypt:ro"
    # network_mode: "host"
    # HASS was originally in the proxy network and could hence resolve mosquitto via its ervice name
    # Since HASS is now in network mode "host" that resolution no longer works.
    # To not have to change the configs inside HASS static IPs are assigned to the docker services
    # and "extra_hosts" provides DNS name "mosquitto" to HASS.
    # extra_hosts:
    #   - "mosquitto:172.21.0.2"
    # devices:
    #   - "/dev/ttyUSB_RfxTrx:/dev/ttyUSB_RfxTrx"
    environment:
      - TZ=Europe/Vienna
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.homeassistant.rule=Host(`homeassistant.puyral.fr`)"
    - "traefik.http.routers.homeassistant.entrypoints=https"
    - "traefik.http.routers.homeassistant.tls.certresolver=ovh"
    - "traefik.http.services.homeassistant.loadbalancer.server.port=8123"
    depends_on:
      - mosquitto
    networks:
      - traefik
      - ha


  zigbee2mqtt:
    image: koenkk/zigbee2mqtt:latest
    container_name: zigbee2mqtt
    restart: always
    stop_grace_period: 2m
    networks:
      - traefik
      - ha
    volumes:
      - /containers/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus_6c969fdb7c12ec119aa120c7bd930c07-if00-port0:/dev/ttyUSB0
    environment:
      TZ: Europe/Vienna
    depends_on:
      - mosquitto
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.zigbee2mqtt.rule=Host(`zigbee2mqtt.puyral.fr`)"
    - "traefik.http.routers.zigbee2mqtt.entrypoints=https"
    - "traefik.http.routers.zigbee2mqtt.tls.certresolver=ovh"
    - "traefik.http.services.zigbee2mqtt.loadbalancer.server.port=8123"

  mosquitto:
    image: "eclipse-mosquitto:latest"
    container_name: "mosquitto"
    restart: always
    stop_grace_period: 2m
    volumes:
      - "/containers/mosquitto:/mosquitto"
    networks:
      - ha
    environment:
      TZ: Europe/Vienna

# A network definition is necessary because homeassistant needs to define the IP or IP range
# of the reverse proxy in the configuration of the http integration.
# It is also necessary for the reverse proxy and to assign static IPs.
networks:
  ha:
  traefik:
    external: true
