name: Nix Build and Check

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  check:
    uses: ./.github/workflows/check.yml
    secrets: inherit

  nixos:
    needs: check
    strategy:
      matrix:
        hostname: [dynas, amdra, ovh-pl, nixomagus, i7, mydos, sandbox]
    uses: ./.github/workflows/build-nixos.yml
    secrets: inherit
    with:
      hostname: ${{ matrix.hostname }}
  
  home-manager:
    needs: check
    strategy:
      matrix:
        include:
          - hostname: vampire
            user: simon
    uses: ./.github/workflows/build-hm.yml
    secrets: inherit
    with:
      hostname: ${{ matrix.hostname }}
      user: ${{ matrix.user }}
